Add upside-down translation
TheNoob27/starboard-languages pull request #12
Opened 2021-04-30 23:31 UTC by doinkythederp

˙sᴉɥʇ ǝʞᴉl 'uʍop ǝpᴉspu ƃuᴉɥʇʎɹǝʌǝ sǝʞɐɯ ʎlpɯᴉS

2021-07-02 02:06 UTC, TheNoob27 requested changes

2021-07-02 02:11 UTC, doinkythederp commented on languages/upside-down.js
> +console.log(module.exports);
Oh yeah, I forgot that was still there

2021-07-02 02:12 UTC, doinkythederp commented on languages/upside-down.js
> +  return (...args) => convertString(func(...args));
Got it

2021-07-02 16:14 UTC, TheNoob27 commented on languages/upside-down.js
> +      flipped[letter] ?? flipped[letter.toLowerCase()] ?? flipped[letter.toUpperCase()] ?? letter;
the thing is, let's look at `help` for example: H and E are quite differently looking than h and e, so it could possibly make things a little funky. Or A and a, r and R, d and D in `starboard`. Idk, maybe it's not as bad as it sounds but I'll have to double check that.

2021-07-03 05:40 UTC, doinkythederp commented on languages/upside-down.js
> +      flipped[letter] ?? flipped[letter.toLowerCase()] ?? flipped[letter.toUpperCase()] ?? letter;
Ideally it wouldn't be a problem because all letters would have flipped versions. It's just there because it would probably better than only some letters being flipped

2021-12-14 00:48 UTC, doinkythederp commented
stale

2021-12-14 00:48 UTC, closed without merging