Finished Spanish Translations😳
TheNoob27/starboard-languages pull request #17
Opened 2021-12-23 00:43 UTC by Vexot

arriba Starboard 😳

2021-12-23 00:44 UTC, Vexot commented
Oops, meant to add this to #15

2021-12-23 11:19 UTC, TheNoob27 commented
I'll be closing the other PR since you've made all the progress here

2021-12-23 11:35 UTC, TheNoob27 requested changes
Thank you for your contribution! It'd be preferred if the locale were to be `es-ES` instead of `es`, to match other languages. Please change the file name too

2021-12-23 11:35 UTC, TheNoob27 commented on index.js
> +    "es"    |
```suggestion
    "es-ES"    |
```

2021-12-23 11:35 UTC, TheNoob27 commented on index.js
> +    "es",
```suggestion
    "es-ES",
```

2021-12-23 11:35 UTC, TheNoob27 commented on languages/en-GB.js
> +    ES: "Spanish",
```suggestion
    ES_ES: "Spanish",
```

2021-12-23 11:35 UTC, TheNoob27 commented on languages/es.js
> +      ES: "Español",
```suggestion
      ES_ES: "Español",
```

2021-12-23 11:35 UTC, TheNoob27 commented on languages/es.js
> +const LOCALE = "es"
```suggestion
const LOCALE = "es-ES"
```

2021-12-23 14:49 UTC, Vexot commented
The requested changes were made

2021-12-25 15:24 UTC, TheNoob27 requested changes

2021-12-25 15:24 UTC, TheNoob27 commented on languages/es-ES.js
> +    HOW: {
```suggestion
    SHOW: {
```

2021-12-25 15:25 UTC, TheNoob27 commented
for each command, you can actually add a NAME key to give the command a spanish alias if you'd like 😁

for example:
```js
    HELP: {
      NAME: "ayuda",
      DESCRIPTION: "...",
      USAGE: "ayuda ([comando])"
```
so `star help` and `star ayuda` would then work! you can feel free to do so

2021-12-25 19:06 UTC, TheNoob27 approved these changes

2021-12-25 20:03 UTC, merged